# Generated by Django 3.2 on 2022-09-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='traveller_count',
        ),
        migrations.AlterField(
            model_name='flight',
            name='fromm',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='to',
            field=models.CharField(max_length=30),
        ),
    ]
