# Generated by Django 3.2 on 2022-09-28 04:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220928_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='datee',
            field=models.DateField(default=datetime.datetime(2022, 9, 28, 4, 23, 16, 707108, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
