# Generated by Django 3.2 on 2022-10-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_flight_datee'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='paym',
            field=models.CharField(default=5832, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
